### PR TITLE
play and pause

### PR DESCRIPTION
**Pull request by AnisyaPurnama**
I have just handlers and listeners file here.

### CODE REVIEW

**Review by sharafcs50 — APPROVED** [review]
Looks Nice, thanks for the great input.

**Comment by krakla** [comment]
Thanks @AnisyaPurnama for sharing us your work. I think you miss to export functions `togglePlay` and `updateButton` in handler `play-and-pause.js`. You already import it in `listerner` file but you didn't export it.

**Comment by AnisyaPurnama** [comment]
@krakla awh yes, you right! thanks abu I will try to fix it

**Comment by colevandersWands** [comment]
@Houcinos , @krakla , Github has a nice way to leave comments on specific lines of code in a PR, this can make it cleaner to give multiple feedbacks on a PR: [video](https://www.youtube.com/watch?v=HW0RPaJqm4g)

@AnisyaPurnama , did you try to run your branch locally?   Of course the whole site won't work because you don't have all the code, but you could already test things like your imports/exports to make sure the names line up

Of course I pick out what could be better : )  Really great work on this project overall!

**Comment by Houcinos** [comment]
Thanks for the tip @colevandersWands 
I saw it yesterday and I tried to use it. However, I thought it will be complicated for others to check it. I will give it a try next time!

**Comment by AnisyaPurnama** [comment]
@Houcinos
 -  okay I will fix the structure 😁 
 - about the logic and init it was from the template, I should have delete that 😅

Thank you for the input houcin! 😃

**Comment by AnisyaPurnama** [comment]
@colevandersWands yes indeed I should have test it first. My bad. 👀

**Pull request closed without merging**
